# Generated by Django 5.1.5 on 2025-04-10 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_amount', models.PositiveIntegerField(default=500)),
                ('is_expired', models.BooleanField(default=False)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ManyToManyField(blank=True, related_name='coupons_used', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
