# Generated by Django 5.1.5 on 2025-04-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_coursepurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_logo', models.ImageField(blank=True, null=True, upload_to='logos/whatsapp')),
                ('facebook_pixel', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sandbox', models.BooleanField(default=True)),
            ],
        ),
    ]
