# Generated by Django 5.1.5 on 2025-01-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
