# Generated by Django 5.1.5 on 2025-02-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='mobile',
        ),
    ]
