# Generated by Django 4.2.4 on 2025-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='in_homepage',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
