# Generated by Django 5.1.5 on 2025-02-18 14:08

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_blogcategory_coursecategory_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('copyright_year', models.PositiveIntegerField(blank=True, default=2025, help_text='Year for copyright (cannot be in the future).', null=True, validators=[Home.models.validate_year])),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('messenger_link', models.URLField(blank=True, null=True, verbose_name='Messenger Link')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter Link')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram Link')),
            ],
        ),
        migrations.CreateModel(
            name='Logosettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='logos/header/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='logos/footer/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logos/favicon/')),
                ('adminlogin_logo', models.ImageField(blank=True, null=True, upload_to='logos/adminlogin/')),
                ('adminsidebar_logo', models.ImageField(blank=True, null=True, upload_to='logos/adminsidebar/')),
            ],
        ),
    ]
