# Generated by Django 5.1.5 on 2025-02-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_businessinfo_logosettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
