# Generated by Django 5.1.5 on 2025-02-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_delete_course_delete_coursecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='show_on_homepage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
