# Generated by Django 5.1.5 on 2025-03-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='brand_logos/')),
            ],
        ),
    ]
